### ISSUE TITLE
Cannot get rake task list when spring server is running

### ISSUE THREAD

**Issue by dsdshcym** [asok/rake#8]
I'm using Spacemacs develop branch.

When the spring server is running, it seems `rake` command cannot get the list of tasks.
I have to stop the spring server and get the rake cache the list.

**Comment by asok** [comment]
What version of spring are you using?

**Comment by dsdshcym** [comment]
Spring version 2.0.1

To be more specific, I get this error when I run `bundle exec spring rake -T -A` under directories other than my project's root directory:
```
Spring was unable to find your config/application.rb file. Your project root was detected at {project_root}/spec/controllers, so spring looked for {project_root}/spec/controllers/config/application.rb but it doesn't exist. You can configure the root of your application by setting Spring.application_root in config/spring.rb.
```

The rake tasks cache can generate correctly when
1. I ran this command under my project's root directory
2. Or I ran `spring rake -T -A` (without `bundle exec`)

I found this issue in spring's repo: https://github.com/rails/spring/issues/323
I don't know if this is due to my configuration or something else.

Thanks for your response and look forward to your advice.

**Comment by asok** [comment]
Actually I cannot re-produce it.

One thing though, the `rake` command should be run from a directory with `Rakefile`. Do you have a `Rakefile` in the root of your project?

**Comment by dsdshcym** [comment]
It's the root directory of my project.

I think it's not an issue of counsel-projectile, then. It might be something wrong with my spring config.
I'll close this issue first and update here if there's anything related to counsel-projectile.

Thanks for your help!

**Comment by asok** [comment]
> It might be something wrong with my spring config

Well if you run `spring rake -T -A` from a shell are you having the same problem?

**Comment by dsdshcym** [comment]
Nope. `spring rake -T -A` can output correctly.

But strangely, only `bundle exec spring rake -T -A` would fail with the error message above.

**Comment by asok** [comment]
> spring rake -T -A can output correctly.

We're talking about running this from a other directory than the root directory?

If you run the same commands from the Emacs' shell? I mean the `ansi-term` in Emacs.

**Comment by dsdshcym** [comment]
Yes, when using `ansi-term`, `spring rake -T -A` can output correctly
when running in another directory and *spring server is already started
in the root directory*.

`spring rake -T -A` would fail in directories other than root directory
if the server is not running.

`bundle exec spring rake -T -A` would fail as long as it's ran in
directories other than root directory, no matter the server is running
or not.

The results are same when using iTerm.

Adam Sokolnicki writes:

**Comment by asok** [comment]
> The results are same when using iTerm.

If that's the case I'm afraid I cannot help here.

**Comment by dsdshcym** [comment]
That's okay.

I found a workaround for now,
1. use `projectile-rails-find-gemfile` to go to gemfile (which is under the
   project root directory)
2. Then use rake commands to cache the task list


Thanks a lot for your kind help. I'll update here if I found the cause
of this issue.

Adam Sokolnicki writes:
